server:
  port: 9090
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#      - id: add_request_parameter_route
#        uri: lb://alibaba-nacos-discovery-client-common
#        filters:
#        - AddRequestParameter=foo, bar
#        predicates:
#          - Method=GET

#      - id: requestratelimiter_route
#        uri: lb://alibaba-nacos-discovery-client-common
#        filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 5
#            redis-rate-limiter.burstCapacity: 10
#            key-resolver: "#{@ipKeyResolver}"
#        predicates:
#          - Method=GET

#      - id: hystrix_route
#        uri: lb://alibaba-nacos-discovery-client-common
#        predicates:
#        - Path=/test
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallback

      - id: retry_test
        uri: lb://alibaba-nacos-discovery-client-common
        predicates:
        - Path=/test
        filters:
        - name: Retry
          args:
            retries: 3
            series:
            - SERVER_ERROR
            methods:
             - GET
             - POST
    nacos:
      discovery:
        server-addr: 192.168.81.131:8848
  redis:
    host: localhost
    port: 6379
    password: 123
logging:
  level:
    org.springframework.cloud.gateway: debug
feign:
  hystrix:
    enabled: true
